@startuml 7-25_10_2023

mix_actor User

User "0..n"-->"0..n"Pricing
(User, Pricing) .. Suscription

Pricing *-- Plan 

Suscription "0..n"-->"0..1"Plan
Suscription "0..n"-->"0..n"AddOn

Plan "0..n"-->"1..n" Feature 
AddOn "0..*"-->"1..n" Feature

Plan "0..n"<--"0..n" AddOn : Available for

Feature <|-- Functional
Feature <|-- NonFunctional

Functional <|-- Information
Functional <|-- Integration
Functional <|-- Tool
Functional <|-- Automation
Functional <|-- Management

NonFunctional <|-- Guarantee
NonFunctional <|-- PaymentOption
NonFunctional <|-- Support

Feature <-- UsageLimit
Plan <-- UsageLimit

UsageLimit <|-- Capacity
UsageLimit <|-- Quota
UsageLimit <|-- Response_Driven
UsageLimit <|-- TimeDriven
UsageLimit <|-- NumberOfUsers

class Plan{
Name: String
Price: Double
Currency: String
HasAnualPayment: Boolean
}

class Feature{
Name: String
}

class Suscription{
StartDate: DateTime
EndDate: DateTime
--
getPrice(): Double
}

@enduml